name: war-room-frontend
region: nyc

services:
  - name: web
    github:
      repo: mxchelsemaan/war-room-frontend
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 80
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
