/**
 * Mock database – completely detached from production data sources.
 * Generated by scripts/generate-mock-db.js
 */

import rawData from './mockDb.json';

export type EntityType = 'Person' | 'Organisation' | 'Place';

export interface Entity {
  name: string;
  type: EntityType;
}

export interface MockArticle {
  id: number;
  source: string;
  date: string;
  title: string;
  summary: string;
  body: string;
  entities: Entity[];
  topics: string[];
}

export const mockDb: MockArticle[] = rawData as MockArticle[];

/** All unique sources, sorted */
export const mockSources = [...new Set(mockDb.map((a) => a.source))].sort();

/** All unique topics, sorted */
export const mockTopics = [...new Set(mockDb.flatMap((a) => a.topics))].sort();

/** All unique entities with their type, sorted by name */
export const mockEntityOptions = (() => {
  const map = new Map<string, EntityType>();
  mockDb.forEach((a) => a.entities.forEach((e) => { if (!map.has(e.name)) map.set(e.name, e.type); }));
  return Array.from(map.entries())
    .map(([name, type]) => ({ name, type }))
    .sort((a, b) => a.name.localeCompare(b.name));
})();

// ---------------------------------------------------------------------------
// Atlas / Map events
// ---------------------------------------------------------------------------

import rawEvents from './mockEvents.json';

export interface EventLocation {
  name: string;
  lat: number;
  lng: number;
}

export interface MapEvent {
  id: number;
  event_type: string;
  event_icon: string;
  event_label: string;
  event_location: EventLocation;
  event_count: number;
  date: string;
}

export interface EventType {
  key: string;
  label: string;
  icon: string;
}

export interface MockEventsData {
  event_types: EventType[];
  events: MapEvent[];
}

const eventsData = rawEvents as MockEventsData;

export const mockEventTypes: EventType[] = eventsData.event_types;
export const mockMapEvents: MapEvent[] = eventsData.events;

// ---------------------------------------------------------------------------
// Article filters — canonical filter shape used across the app
// ---------------------------------------------------------------------------

export interface ArticleFilters {
  q: string;
  sources: string[];
  topics: string[];
  entityNames: string[];
  dateFrom: string;
  dateTo: string;
}

export const EMPTY_ARTICLE_FILTERS: ArticleFilters = {
  q: "",
  sources: [],
  topics: [],
  entityNames: [],
  dateFrom: "",
  dateTo: "",
};

export function applyFilters(articles: MockArticle[], filters: ArticleFilters): MockArticle[] {
  const q = filters.q.trim().toLowerCase();
  return articles.filter((a) => {
    if (filters.sources.length > 0 && !filters.sources.includes(a.source)) return false;
    if (filters.topics.length > 0 && !a.topics.some((t) => filters.topics.includes(t))) return false;
    if (filters.entityNames.length > 0 && !a.entities.some((e) => filters.entityNames.includes(e.name))) return false;
    if (filters.dateFrom && a.date < filters.dateFrom) return false;
    if (filters.dateTo && a.date > filters.dateTo) return false;
    if (q) {
      const hit =
        a.title.toLowerCase().includes(q) ||
        a.summary.toLowerCase().includes(q) ||
        a.body.includes(filters.q.trim());
      if (!hit) return false;
    }
    return true;
  });
}

// ---------------------------------------------------------------------------
// Saved feeds
// ---------------------------------------------------------------------------

export interface SavedFeed {
  id: string;
  name: string;
  filters: {
    sources: string[];
    topics: string[];
    entityNames: string[];
  };
}

/** Pre-seeded "saved feeds" – replace with Supabase rows later */
export const MOCK_FEEDS: SavedFeed[] = [
  { id: "feed-all",         name: "All Lebanon coverage",        filters: { sources: [], topics: [], entityNames: [] } },
  { id: "feed-gaza",        name: "Gaza ceasefire talks",        filters: { sources: [], topics: ["Gaza ceasefire talks"], entityNames: [] } },
  { id: "feed-hezbollah",   name: "Hezbollah southern front",    filters: { sources: [], topics: ["Hezbollah southern front"], entityNames: [] } },
  { id: "feed-lorient",     name: "English-language press",      filters: { sources: ["L'Orient Today", "The Daily Star Lebanon", "The961"], topics: [], entityNames: [] } },
  { id: "feed-presidential",name: "Lebanon presidential vacuum", filters: { sources: [], topics: ["Lebanon presidential vacuum"], entityNames: [] } },
  { id: "feed-pound",       name: "Lebanese pound devaluation",  filters: { sources: [], topics: ["Lebanese pound devaluation"], entityNames: [] } },
  { id: "feed-iran",        name: "Iranian proxy networks",      filters: { sources: [], topics: ["Iranian proxy networks"], entityNames: [] } },
];

/** Apply a feed's filters to an article list */
export function applyFeedFilters(articles: MockArticle[], feed: SavedFeed): MockArticle[] {
  return applyFilters(articles, { ...EMPTY_ARTICLE_FILTERS, ...feed.filters });
}

/** Cached article counts per feed – computed once at module load */
export const feedArticleCounts: Record<string, number> = Object.fromEntries(
  MOCK_FEEDS.map((f) => [f.id, applyFeedFilters(mockDb, f).length]),
);
